# Generated by Django 4.2.4 on 2023-09-08 07:01

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path)),
                ('active', models.BooleanField(default=True, help_text='Display this banner on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
