# Generated by Django 4.2.5 on 2023-10-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
