# Generated by Django 4.2.5 on 2023-10-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_delete_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='small_description',
            field=models.TextField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
