# Generated by Django 4.2.5 on 2023-10-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='status',
            field=models.BooleanField(default=True, help_text='0=hidden,1=show'),
        ),
    ]
