# Generated by Django 4.2.5 on 2023-10-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_testimonial_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='active',
        ),
        migrations.AddField(
            model_name='banner',
            name='status',
            field=models.BooleanField(default=True, help_text='0=hidden,1=show'),
        ),
    ]
