# Generated by Django 4.2.5 on 2023-10-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_media',
            name='status',
            field=models.BooleanField(default=False, help_text='0=default,1=Hidden'),
        ),
    ]
