# Generated by Django 4.2.5 on 2023-10-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_social_media_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social_media',
        ),
    ]
