# Generated by Django 4.2.5 on 2023-10-25 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_coupon_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
