# Generated by Django 4.2.5 on 2023-10-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price_after_discount',
            field=models.FloatField(null=True),
        ),
    ]
