# Generated by Django 4.2.5 on 2023-10-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_order_total_price_after_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_usage',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
