# Generated by Django 4.2.5 on 2023-10-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_profile_used_coupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='used_coupons',
        ),
    ]
